# GitHub Actions CI for building and testing Opsctrl CLI

name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.6.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 build-essential automake libtool pkg-config

      - name: Install dependencies
        run: npm ci

      - name: Build binary with Nexe
        run: npm run build

      - name: Show binary version
        run: |
          chmod +x ./opsctrl
          ./opsctrl --version

      - name: Test install script flow
        run: |
          curl -sSL https://opsctrl.dev/install.sh | bash -s -- v${{ matrix.node-version }}
          opsctrl --help

      - name: Run lint and tests
        run: |
          npm run lint || true
          npm test || true
